# Generated by Django 5.1.5 on 2025-02-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenGem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Drink', 'Drink'), ('Park', 'Park'), ('Art', 'Art'), ('Attractions', 'Attractions'), ('Nightlife', 'Nightlife'), ('Music', 'Music'), ('Theatre', 'Theatre'), ('Museums', 'Museums')], default='Food', max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
