# Generated by Django 5.1.5 on 2025-02-04 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiddengem',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.CreateModel(
            name='Activty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('like', models.IntegerField(default=0)),
                ('hiddengem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hiddengem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
