# Generated by Django 5.1.5 on 2025-02-14 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_comment_alter_activity_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenttext',
            new_name='comment',
        ),
    ]
