# Generated by Django 5.1.5 on 2025-02-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_commenttext_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='comment',
        ),
    ]
